repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: '\.(py)$'
        exclude: 'src/edsger/.*\.pyx$'

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.16.2
    hooks:
      - id: cython-lint
        files: '\.(pyx|pxd)$'
        args: [--max-line-length=88]